-- Chosen SERP copy for core public pages (overwrites existing rows for these paths).
-- Run after 052. Uses UPSERT so 006/052 DO NOTHING seeds are replaced here.

INSERT INTO seo_pages (
  page_path, page_type, meta_title, meta_description, focus_keyword, canonical_url,
  og_title, og_description, twitter_title, twitter_description, robots_meta
)
VALUES
  ('/', 'page',
   'Student Accommodation Preston | En-Suite Rooms - Urban Hub',
   'Urban Hub Preston offers modern en-suite rooms minutes from University of Lancashire, with bills included and no guarantor needed upfront. Book your viewing today.',
   'student accommodation Preston',
   'https://urbanhub.uk/',
   'Student Accommodation Preston | En-Suite Rooms - Urban Hub',
   'Urban Hub Preston offers modern en-suite rooms minutes from University of Lancashire, with bills included and no guarantor needed upfront. Book your viewing today.',
   'Student Accommodation Preston | En-Suite Rooms - Urban Hub',
   'Urban Hub Preston offers modern en-suite rooms minutes from University of Lancashire, with bills included and no guarantor needed upfront. Book your viewing today.',
   'index, follow'),
  ('/about', 'page',
   'Why Students Choose Urban Hub Preston | More Than a Room',
   'Urban Hub Preston is a 425-bed student residence near the University of Lancashire, offering on-site support, social spaces, and a genuine sense of community. Learn more.',
   'Urban Hub Preston',
   'https://urbanhub.uk/about',
   'Why Students Choose Urban Hub Preston | More Than a Room',
   'Urban Hub Preston is a 425-bed student residence near the University of Lancashire, offering on-site support, social spaces, and a genuine sense of community. Learn more.',
   'Why Students Choose Urban Hub Preston | More Than a Room',
   'Urban Hub Preston is a 425-bed student residence near the University of Lancashire, offering on-site support, social spaces, and a genuine sense of community. Learn more.',
   'index, follow'),
  ('/blog', 'page',
   'Urban Hub Blog | Student Tips, University of Lancashire',
   'From budgeting tips to the best spots near University of Lancashire, the Urban Hub blog has everything you need for student life in Preston. Read on now.',
   'student life Preston',
   'https://urbanhub.uk/blog',
   'Urban Hub Blog | Student Tips, University of Lancashire',
   'From budgeting tips to the best spots near University of Lancashire, the Urban Hub blog has everything you need for student life in Preston. Read on now.',
   'Urban Hub Blog | Student Tips, University of Lancashire',
   'From budgeting tips to the best spots near University of Lancashire, the Urban Hub blog has everything you need for student life in Preston. Read on now.',
   'index, follow'),
  ('/short-term', 'page',
   'Short Term Student Stays in Preston | Urban Hub Rooms',
   'Visiting Preston or need a short stay near University of Lancashire? Urban Hub offers furnished short-term rooms with bills included. Enquire with us today.',
   'short term student stays Preston',
   'https://urbanhub.uk/short-term',
   'Short Term Student Stays in Preston | Urban Hub Rooms',
   'Visiting Preston or need a short stay near University of Lancashire? Urban Hub offers furnished short-term rooms with bills included. Enquire with us today.',
   'Short Term Student Stays in Preston | Urban Hub Rooms',
   'Visiting Preston or need a short stay near University of Lancashire? Urban Hub offers furnished short-term rooms with bills included. Enquire with us today.',
   'index, follow'),
  ('/vr-tour', 'page',
   'Take a Virtual Tour of Urban Hub Preston Rooms Online',
   'Can''t visit Preston in person? Take a 360° virtual tour of Urban Hub and see your future room from anywhere in the world. Start your virtual tour now.',
   'Urban Hub VR tour',
   'https://urbanhub.uk/vr-tour',
   'Take a Virtual Tour of Urban Hub Preston Rooms Online',
   'Can''t visit Preston in person? Take a 360° virtual tour of Urban Hub and see your future room from anywhere in the world. Start your virtual tour now.',
   'Take a Virtual Tour of Urban Hub Preston Rooms Online',
   'Can''t visit Preston in person? Take a 360° virtual tour of Urban Hub and see your future room from anywhere in the world. Start your virtual tour now.',
   'index, follow'),
  ('/reviews', 'page',
   'Urban Hub Preston Reviews | Hear From Our Residents',
   'See what students are really saying about Urban Hub Preston, from the rooms to the community to moving-in day itself. Read genuine reviews right now.',
   'Urban Hub Preston reviews',
   'https://urbanhub.uk/reviews',
   'Urban Hub Preston Reviews | Hear From Our Residents',
   'See what students are really saying about Urban Hub Preston, from the rooms to the community to moving-in day itself. Read genuine reviews right now.',
   'Urban Hub Preston Reviews | Hear From Our Residents',
   'See what students are really saying about Urban Hub Preston, from the rooms to the community to moving-in day itself. Read genuine reviews right now.',
   'index, follow'),
  ('/faq', 'page',
   'FAQs | Urban Hub Preston Student Accommodation Info',
   'Answers to the most common questions about booking, bills, contracts, and living at Urban Hub Preston. Find everything you need to know before you apply.',
   'Urban Hub Preston FAQ',
   'https://urbanhub.uk/faq',
   'FAQs | Urban Hub Preston Student Accommodation Info',
   'Answers to the most common questions about booking, bills, contracts, and living at Urban Hub Preston. Find everything you need to know before you apply.',
   'FAQs | Urban Hub Preston Student Accommodation Info',
   'Answers to the most common questions about booking, bills, contracts, and living at Urban Hub Preston. Find everything you need to know before you apply.',
   'index, follow'),
  ('/contact', 'page',
   'Contact Urban Hub Preston | Get in Touch Today Now',
   'Get in touch with Urban Hub Preston for viewings, availability, or anything else you need to know. Our team replies fast, every single day of the week.',
   'contact Urban Hub Preston',
   'https://urbanhub.uk/contact',
   'Contact Urban Hub Preston | Get in Touch Today Now',
   'Get in touch with Urban Hub Preston for viewings, availability, or anything else you need to know. Our team replies fast, every single day of the week.',
   'Contact Urban Hub Preston | Get in Touch Today Now',
   'Get in touch with Urban Hub Preston for viewings, availability, or anything else you need to know. Our team replies fast, every single day of the week.',
   'index, follow'),
  ('/studios/2026-2027', 'page',
   'Book Your Studio for 2026/27 | Urban Hub Preston Now',
   'Your own space, sorted. Modern studio apartments at Urban Hub Preston for 2026/27, fully furnished, bills included. Rooms are going fast, apply today.',
   'student studios 2026/27 Preston',
   'https://urbanhub.uk/studios/2026-2027',
   'Book Your Studio for 2026/27 | Urban Hub Preston Now',
   'Your own space, sorted. Modern studio apartments at Urban Hub Preston for 2026/27, fully furnished, bills included. Rooms are going fast, apply today.',
   'Book Your Studio for 2026/27 | Urban Hub Preston Now',
   'Your own space, sorted. Modern studio apartments at Urban Hub Preston for 2026/27, fully furnished, bills included. Rooms are going fast, apply today.',
   'index, follow')
ON CONFLICT (page_path) DO UPDATE SET
  page_type = EXCLUDED.page_type,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  focus_keyword = EXCLUDED.focus_keyword,
  canonical_url = EXCLUDED.canonical_url,
  og_title = EXCLUDED.og_title,
  og_description = EXCLUDED.og_description,
  twitter_title = EXCLUDED.twitter_title,
  twitter_description = EXCLUDED.twitter_description,
  robots_meta = EXCLUDED.robots_meta,
  updated_at = NOW();
